SYSTARG=Android
<../../mkconfig
#SYSTARG=Android

#Configurable parameters
LIB=emu

CONF=emu			#default configuration
CONFLIST=emu
CLEANCONFLIST=

INSTALLDIR=$ROOT/$SYSTARG/$OBJTYPE/bin	#path of directory where kernel is installed

#end configurable parameters

X11LIBS= -lX11 -lXext	# can remove or override using env section in config files

<$ROOT/mkfiles/mkfile-$SYSTARG-$OBJTYPE	#set vars based on target system

<| $SHELLNAME ../port/mkdevlist $CONF	#sets $IP, $DEVS, $PORT, $LIBS
<mkfile-$OBJTYPE	# sets $ARCHFILES

OBJ=\
	asm-$OBJTYPE.$O\
	$ARCHFILES\
	os.$O\
	kproc-pthreads.$O\
	segflush-$OBJTYPE.$O\
	$CONF.root.$O\
	lock.$O\
	telldir.$O\
	getdtablesize.$O\
	$DEVS\
	$PORT\

LIBNAMES=${LIBS:%=lib%.a}
#libs=${LIBS:%=$ROOT/$OBJDIR/lib/lib%.a}

HFILES=\

CFLAGS='-DROOT="'$ROOT'"' -DEMU -I. -I../port -I$ROOT/$SYSTARG/$OBJTYPE/include -I$ROOT/include -I$ROOT/libinterp $CTHREADFLAGS $CFLAGS $EMUOPTIONS
#SYSLIBS= $X11LIBS -lm -lpthread
SYSLIBS= -lm
KERNDATE=`{$NDATE}

#default:V:	$O.$CONF

#$O.$CONF:	$OBJ $CONF.c $CONF.root.h $LIBNAMES
#	$CC $CFLAGS '-DKERNDATE='$KERNDATE $CONF.c
#	$LD $LDFLAGS -o $target $OBJ $CONF.$O $LIBFILES $SYSLIBS

#install:V: $O.$CONF
#	cp $O.$CONF $INSTALLDIR/$CONF


<../port/portmkfile

devfs.$O:	../port/devfs-posix.c









LIBDIR=$ROOT/$OBJDIR/lib
LIBRARY=$LIBDIR/$LIB.a
LIBOBJ=${OFILES:%=$LIBRARY(%)}

default:V:	all

all install:V:	$LIBRARY

installall:V:
	for (objtype in $CPUS)
		mk $MKFLAGS install

clean:V:	clean-std	

nuke:V:		nuke-std

LIB1=${LIBRARY:%=$ARPREFIX%}

$LIBRARY:	$OBJ $CONF.c $CONF.root.h $LIBNAMES #$LIBOBJ $OFILES
	$CC $CFLAGS '-DKERNDATE='$KERNDATE $CONF.c
	$AR $ARFLAGS $LIB1 $OBJ $CONF.$O   #$LIBFILES  #$OFILES

$LIBRARY(%.$O):N:	%.$O








#telldir.$O:	./compat/telldir.c

#getdtablesize.$O:	./compat/getdtablesize.c

#<$ROOT/mkfiles/mksyslib-$SHELLTYPE

